version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.9-bullseye"
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    networks:
      - swarm-dev
    environment:
      - DOCKER_HOST=unix:///var/run/docker-host.sock
    depends_on:
      - redis
      - postgres
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - swarm-dev
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: swarm_arena
      POSTGRES_USER: swarm_user
      POSTGRES_PASSWORD: swarm_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - swarm-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swarm_user -d swarm_arena"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  ray-head:
    image: rayproject/ray:2.8.0-py39
    ports:
      - "10001:10001"  # Ray Dashboard
      - "8265:8265"    # Ray Client Server
    command: ray start --head --dashboard-host=0.0.0.0 --dashboard-port=10001 --block
    volumes:
      - ../..:/workspace:cached
    networks:
      - swarm-dev
    environment:
      RAY_DISABLE_USAGE_STATS: 1
      RAY_DEDUP_LOGS: 0
    healthcheck:
      test: ["CMD", "python", "-c", "import ray; ray.init('auto'); print('Ray OK')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data:
  postgres-data:

networks:
  swarm-dev:
    driver: bridge