
# Production values for Swarm Arena
replicaCount: 3

image:
  repository: terragon/swarm-arena
  tag: "v1.0.0"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "1000"
  hosts:
    - host: api.terragon.ai
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: terragon-tls
      hosts:
        - api.terragon.ai

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 1000m
    memory: 2Gi

monitoring:
  enabled: true
  prometheusPort: 9090
  grafanaPort: 3000

security:
  networkPolicies:
    enabled: true
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

config:
  environment: production
  logLevel: INFO
  maxConcurrentSimulations: 50
  simulationTimeout: 300
